---
title: "Project Progress Reports"
tbl-colwidths: [20, 5, 10]
---
## Overview
At the end of each module, you will have one week to submit your responses to guided questions on how you will integrate new concepts into your final project. I **highly** encourage you to work on these during the module to stay on track with your project.

Note that the Gaps module does not have a progress report.

## Schedule
| Module | Instructions | Due Date |
|:------:|:------------:|:--------:|
| Overview | [{{< fa sharp pen-field >}}](../updates/overview.qmd) | 9/26/25 |
| Uncertainty | [{{< fa sharp pen-field >}}](../updates/uncertainty.qmd) | 10/3/25 |
| RDM | [{{< fa sharp pen-field >}}](../updates/rdm.qmd) | 10/10/25 |
| Trade-offs | [{{< fa sharp pen-field >}}](../updates/tradeoffs.qmd) | 10/17/25 |
| DMDU | {{< fa sharp pen-field >}} | 11/14/25 |

## Rubric
Your grade is based on your perceived effort. Even if you do not fully understand how to apply lessons from a module to your project, you can receive full credit for a report if you understand your knowledge gaps and form strong questions for me to provide clarification and direction for you. You can receive 0-3 points on each assignment.

* 0: No perceived effort 
* 1: Low perceived effort
  - E.g., incomplete, no synthesis, no self awareness of knowledge gaps, no questions for me
* 2: Moderate perceived effort   
  - E.g., Complete but synthesis has important shortcomings and questions are too open ended for me to provide helpful guidance
* 3: High perceived effort
  - E.g., Complete and synthesis has important shortcomings but questions are specific and allow me to provide helpful guidance. 

The instructions for each report will include examples of specific questions about the module that you can use *for free* in your report to help boost your grade. I will not be able to anticipate all questions that apply to your understanding and decision problem, so it is no guarantee you receive a 3 if you use some of these example questions. 

I will provide as much detailed feedback on each report as I can. This means that the more thought and effort you put into your report, the more guidance you will receive. This will help you on your project presentation and report. However, you must apply discretion when writing your report and should not include too much or irrelevant details. Concision is a very important feature of strong synthesis. 

Late submissions receive a 25% downgrading of the full credit score for each l ate day. Extension requests must be made 24 hours before the submission deadline with a submission of what you have achieved so far.