---
title: "Lab 3: Addressing Uncertainty in Multisector Dynamics Tutorials"
author: "ENGS 199.20"
date: last-modified
format:
    html:        
        warning: true
        error: true
        code-fold: true
    ipynb:
        warning: true
        error: true
execute: 
    echo: true
    enabled: true
jupyter: engs199
engine: jupyter
sidebar: main
---

## Overview
Today we're going to get comfortable running code for uncertainty analysis and apply relevant methods to our decision analysis problem. 

Today's objectives:

1. Reproduce the MSD UC/UQ book Python environment locally 
2. Choose a tutorial that resonates with you and run its code
3. Demonstrate your conceptual understanding of the analysis you ran and its interpretation
4. (Optional) Apply the workflow from the tutorial to your project data

## Lab Workflow

### GitHub Repository Setup

We are interested in running the MSD e-book tutorials locally, so we will adapt the [contribution](https://uc-ebook.org/dev/docs/html/contributing.html#development-workflow) instructions for this purpose. 

1. Fork the [MSD Uncertainty e-book](https://github.com/IMMM-SFA/msd_uncertainty_ebook/fork) then clone it locally
2. Create a `conda` or `mamba` environment with a compatible Python version for the e-book. You can check the compatible Python versions [here](https://github.com/IMMM-SFA/msd_uncertainty_ebook/blob/dev/pyproject.toml#L10). I created an environment `ucuq_book` with python version 3.12 and was able to run the notebooks locally. 
3. Make sure your environment is activated and `cd` to your local repository. Run `pip install .` to install all the packages you need to run the tutorials. I also installed `ipykernel` to set up the environment as a kernel and run the code in VSCode. 

### Choose the tutorial to run and adapt for your project data

Take a look at the [online tutorials](https://uc-ebook.org/docs/html/A2_Jupyter_Notebooks.html) and identify the uncertainty analyses that you can envision running with your project data. Pick the one that you feel is the most relevant for your decision analysis goals and run this notebook locally. If you feel that none of these tutorials map well to your goals, let's chat ;) 

### Run the uncertainty analysis you chose on your project data

This is optional, but recommended. It is likely easier for you to run the uncertainty analysis in the directory where you work on your decision analysis. Figure out which packages to install into your project environment to run the uncertainty analysis you tried out in the previous step. Apply this uncertainty analysis with your decision analysis model. You do not have to successfully execute the uncertainty analysis to receive the full grade on this lab, but I recommend you try because it is more synergistic with your project than running code for a generic tutorial.  

### Explain the uncertainty analysis you ran and its interpretation

For your lab report, please submit a concise write-up on the uncertainty analysis you ran and its interpretation for the underlying data. I recommend calibrating your writing content and tone for manuscript style (e.g., see the "Sensitivity Analysis" section of the Methods in [this paper](https://www.nature.com/articles/s41467-020-19188-9#Sec8) and also see how the authors interpret the results of this procedure in the Results subsection "Uncertainties that drive the variance of projected damages"). I expect the following qualities in your text:

* a clear English explanation of the analysis plan 
  - this includes emphasizing what question(s) the analysis addresses and why it is appropriate for the problem at hand
* justification of the chosen sampling plan and sample size
* specific reference to the analysis results
  - e.g., include a figure (or more than one) in your report
* thoughtful interpretation
  - this includes highlighting key assumptions
* accurate references
  - you might only cite the MSD book and references within it, but you might also find it helpful to look beyond those

If you ran the analysis on your project data, you only have to explain the analysis and interpretation for that example. 

### Submit your lab report

For the online training, you can send me the pdf of your lab report. I do not need to see any code, but you are welcome to share your repositories with me if you would like me to take a look. I recommend wrapping up your notebook and lab report into a GitHub repository so that you can bolster your online portfolio, but I understand that this is time-intensive so it is not required.