---
format:
  html:
    title: Week 2 Readings

reference-location: document
citation-location: document
sidebar: main
---

## Required Reading

1. @Oddo-etal-2020

    - This article builds on a classic decision analysis framework by incorporating key uncertainties and multiple objectives, demonstrating how these considerations affect the representation of "optimal" strategies. It clearly distinguishes between "deep" and "shallow" uncertainties, and includes a global sensitivity analysis on how uncertainty in parameters influence objective evaluation. Table 1 is great. 

## Optional Reading

I want to provide you with more references for identifying, characterizing, and quantifying uncertainties in general and in decision analysis papers. 

More on uncertainty analysis in general: @Srikrishnan-etal-2022 and related [e-book on uncertainty characterization and quantification in MSD analyses](https://uc-ebook.org/docs/html/index.html)

More on deep uncertainty: @Lempert-etal-2024

Papers with Methods sections (or Supplementary Info) worth reviewing to help with your module progress report (look at the presentation of the analysis workflow, how the authors represent and account for various types of uncertainty, etc.,):

- @Oddo-etal-2020
- @Zarekarizi-etal-2020
- @Pollack-etal-2025


### References
::: {#refs}
:::